services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: postgres
      POSTGRES_DB: nba_db
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nba_watchability_index:/code
    ports:
      - 8000:8000
    depends_on:
      - db
