services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: postgres
      POSTGRES_DB: nba_db
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    entrypoint: /startup_scripts/entrypoint.sh
    volumes:
      - ./nba_watchability_index:/code
      - ./startup_scripts:/startup_scripts
      - .env:/code/.env
    ports:
      - 8000:8000
    depends_on:
      - db
