# Generated by Django 4.2.17 on 2025-02-27 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.team')),
            ],
            options={
                'unique_together': {('player', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', through='data.PlayerTeam', to='data.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='data.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='data.team'),
        ),
    ]
