FROM python:3.9

# USER app
RUN apt update && apt install postgresql-client -y && apt clean

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
